name: deploy app to testflight
on:
  push:
    branches: [testflight_release]

jobs:
  build_and_deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      # - name: Bundle install
      #   run: |
      #     cd ./ios
      #     gem install --user-install bundler
      #     bundle config set path 'vendor/bundle'
      #     bundle install
      - run: ls ./ios
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master'
          architecture: x64
      - name: Install tools
        run: |
          flutter pub get
          cd ./ios
          flutter precache --ios 
          pod install --repo-update
      - name: Upload to testflight
        run:
          cd ./ios
          fastlane ios upload_to_tf

  