name: deploy app to testflight
on:
  push:
    branches: [testflight_release]

jobs:
  build_and_deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Bundle install
        run: |
          cd ./ios
          gem install --user-install bundler
          bundle config set path 'vendor/bundle'
          bundle install
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: dart-lang/setup-dart@v2.18.0
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.4'
          architecture: arm64
      - name: Install tools
        run: |
          flutter pub get
          cd ./ios && pod install
      - name: Upload to testflight
        run: 
          bundle exec fastlane ios upload_to_tf

  